// Package srn provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package srn

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TMDBResultMediaType.
const (
	Movie TMDBResultMediaType = "movie"
	Tv    TMDBResultMediaType = "tv"
)

// Valid indicates whether the value is a known member of the TMDBResultMediaType enum.
func (e TMDBResultMediaType) Valid() bool {
	switch e {
	case Movie:
		return true
	case Tv:
		return true
	default:
		return false
	}
}

// Challenge PoW challenge — present on 401/403 when proof-of-work is required
type Challenge struct {
	// K Number of leading zero hex chars required
	K int `json:"k"`

	// Salt Hex HMAC salt tied to IP and time window
	Salt string `json:"salt"`
}

// ChallengeResponse defines model for ChallengeResponse.
type ChallengeResponse struct {
	// K Number of leading zero hex chars required
	K int `json:"k"`

	// Salt Hex HMAC salt tied to IP and time window
	Salt string `json:"salt"`

	// Vip Whether the client is a VIP
	Vip bool `json:"vip"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Challenge PoW challenge — present on 401/403 when proof-of-work is required
	Challenge *Challenge `json:"challenge,omitempty"`
	Error     string     `json:"error"`
}

// SRNEvent defines model for SRNEvent.
type SRNEvent struct {
	ArchiveMd5 *string `json:"archive_md5,omitempty"`
	ContentMd5 string  `json:"content_md5"`
	CreatedAt  int     `json:"created_at"`
	EpisodeNum *int    `json:"episode_num,omitempty"`
	Id         string  `json:"id"`
	Kind       int     `json:"kind"`
	Language   *string `json:"language,omitempty"`
	Pubkey     string  `json:"pubkey"`
	SeasonNum  *int    `json:"season_num,omitempty"`
	Sig        string  `json:"sig"`
	SourceType *string `json:"source_type,omitempty"`
	SourceUri  *string `json:"source_uri,omitempty"`

	// Tags JSON-encoded tag array
	Tags   string  `json:"tags"`
	TmdbId *string `json:"tmdb_id,omitempty"`
}

// TMDBResult defines model for TMDBResult.
type TMDBResult struct {
	FirstAirDate string              `json:"first_air_date"`
	Id           int                 `json:"id"`
	MediaType    TMDBResultMediaType `json:"media_type"`
	Name         string              `json:"name"`
	PosterPath   *string             `json:"poster_path"`
	ReleaseDate  string              `json:"release_date"`
	Title        string              `json:"title"`
}

// TMDBResultMediaType defines model for TMDBResult.MediaType.
type TMDBResultMediaType string

// GetV1EventsParams defines parameters for GetV1Events.
type GetV1EventsParams struct {
	Tmdb       *string `form:"tmdb,omitempty" json:"tmdb,omitempty"`
	Season     *string `form:"season,omitempty" json:"season,omitempty"`
	Ep         *string `form:"ep,omitempty" json:"ep,omitempty"`
	Language   *string `form:"language,omitempty" json:"language,omitempty"`
	Kind       *string `form:"kind,omitempty" json:"kind,omitempty"`
	Pubkey     *string `form:"pubkey,omitempty" json:"pubkey,omitempty"`
	ArchiveMd5 *string `form:"archive_md5,omitempty" json:"archive_md5,omitempty"`

	// XSrnPubkey Client Ed25519 public key (hex)
	XSrnPubkey *string `json:"x-srn-pubkey,omitempty"`

	// XSrnNonce Proof-of-Work nonce
	XSrnNonce *string `json:"x-srn-nonce,omitempty"`

	// XSrnSignature Request signature (hex)
	XSrnSignature *string `json:"x-srn-signature,omitempty"`
}

// PostV1EventsMultipartBody defines parameters for PostV1Events.
type PostV1EventsMultipartBody struct {
	Event string      `json:"event"`
	File  interface{} `json:"file,omitempty"`
}

// PostV1EventsParams defines parameters for PostV1Events.
type PostV1EventsParams struct {
	// XSrnPubkey Client Ed25519 public key (hex)
	XSrnPubkey *string `json:"x-srn-pubkey,omitempty"`

	// XSrnNonce Proof-of-Work nonce
	XSrnNonce *string `json:"x-srn-nonce,omitempty"`

	// XSrnSignature Request signature (hex)
	XSrnSignature *string `json:"x-srn-signature,omitempty"`
}

// GetV1EventsIdContentParams defines parameters for GetV1EventsIdContent.
type GetV1EventsIdContentParams struct {
	// XSrnPubkey Client Ed25519 public key (hex)
	XSrnPubkey *string `json:"x-srn-pubkey,omitempty"`

	// XSrnNonce Proof-of-Work nonce
	XSrnNonce *string `json:"x-srn-nonce,omitempty"`

	// XSrnSignature Request signature (hex)
	XSrnSignature *string `json:"x-srn-signature,omitempty"`
}

// GetV1TmdbSearchParams defines parameters for GetV1TmdbSearch.
type GetV1TmdbSearchParams struct {
	// Q Search query
	Q string `form:"q" json:"q"`

	// Fresh Bypass cache (set to 1)
	Fresh *string `form:"fresh,omitempty" json:"fresh,omitempty"`

	// XSrnPubkey Client Ed25519 public key (hex)
	XSrnPubkey *string `json:"x-srn-pubkey,omitempty"`

	// XSrnNonce Proof-of-Work nonce
	XSrnNonce *string `json:"x-srn-nonce,omitempty"`

	// XSrnSignature Request signature (hex)
	XSrnSignature *string `json:"x-srn-signature,omitempty"`
}

// GetV1TmdbSeasonParams defines parameters for GetV1TmdbSeason.
type GetV1TmdbSeasonParams struct {
	TmdbId string `form:"tmdb_id" json:"tmdb_id"`
	Season string `form:"season" json:"season"`

	// XSrnPubkey Client Ed25519 public key (hex)
	XSrnPubkey *string `json:"x-srn-pubkey,omitempty"`

	// XSrnNonce Proof-of-Work nonce
	XSrnNonce *string `json:"x-srn-nonce,omitempty"`

	// XSrnSignature Request signature (hex)
	XSrnSignature *string `json:"x-srn-signature,omitempty"`
}

// PostV1EventsMultipartRequestBody defines body for PostV1Events for multipart/form-data ContentType.
type PostV1EventsMultipartRequestBody PostV1EventsMultipartBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1Challenge request
	GetV1Challenge(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Events request
	GetV1Events(ctx context.Context, params *GetV1EventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1EventsWithBody request with any body
	PostV1EventsWithBody(ctx context.Context, params *PostV1EventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1EventsIdContent request
	GetV1EventsIdContent(ctx context.Context, id string, params *GetV1EventsIdContentParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Relay request
	GetV1Relay(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1TmdbSearch request
	GetV1TmdbSearch(ctx context.Context, params *GetV1TmdbSearchParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1TmdbSeason request
	GetV1TmdbSeason(ctx context.Context, params *GetV1TmdbSeasonParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1Challenge(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ChallengeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Events(ctx context.Context, params *GetV1EventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1EventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1EventsWithBody(ctx context.Context, params *PostV1EventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1EventsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1EventsIdContent(ctx context.Context, id string, params *GetV1EventsIdContentParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1EventsIdContentRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Relay(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1RelayRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1TmdbSearch(ctx context.Context, params *GetV1TmdbSearchParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1TmdbSearchRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1TmdbSeason(ctx context.Context, params *GetV1TmdbSeasonParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1TmdbSeasonRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1ChallengeRequest generates requests for GetV1Challenge
func NewGetV1ChallengeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/challenge")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1EventsRequest generates requests for GetV1Events
func NewGetV1EventsRequest(server string, params *GetV1EventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Tmdb != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tmdb", *params.Tmdb, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Season != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "season", *params.Season, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Ep != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ep", *params.Ep, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Kind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "kind", *params.Kind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Pubkey != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pubkey", *params.Pubkey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ArchiveMd5 != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "archive_md5", *params.ArchiveMd5, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XSrnPubkey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-srn-pubkey", *params.XSrnPubkey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-pubkey", headerParam0)
		}

		if params.XSrnNonce != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-srn-nonce", *params.XSrnNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-nonce", headerParam1)
		}

		if params.XSrnSignature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "x-srn-signature", *params.XSrnSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-signature", headerParam2)
		}

	}

	return req, nil
}

// NewPostV1EventsRequestWithBody generates requests for PostV1Events with any type of body
func NewPostV1EventsRequestWithBody(server string, params *PostV1EventsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XSrnPubkey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-srn-pubkey", *params.XSrnPubkey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-pubkey", headerParam0)
		}

		if params.XSrnNonce != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-srn-nonce", *params.XSrnNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-nonce", headerParam1)
		}

		if params.XSrnSignature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "x-srn-signature", *params.XSrnSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-signature", headerParam2)
		}

	}

	return req, nil
}

// NewGetV1EventsIdContentRequest generates requests for GetV1EventsIdContent
func NewGetV1EventsIdContentRequest(server string, id string, params *GetV1EventsIdContentParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/events/%s/content", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XSrnPubkey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-srn-pubkey", *params.XSrnPubkey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-pubkey", headerParam0)
		}

		if params.XSrnNonce != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-srn-nonce", *params.XSrnNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-nonce", headerParam1)
		}

		if params.XSrnSignature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "x-srn-signature", *params.XSrnSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-signature", headerParam2)
		}

	}

	return req, nil
}

// NewGetV1RelayRequest generates requests for GetV1Relay
func NewGetV1RelayRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/relay")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1TmdbSearchRequest generates requests for GetV1TmdbSearch
func NewGetV1TmdbSearchRequest(server string, params *GetV1TmdbSearchParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tmdb/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Fresh != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fresh", *params.Fresh, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XSrnPubkey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-srn-pubkey", *params.XSrnPubkey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-pubkey", headerParam0)
		}

		if params.XSrnNonce != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-srn-nonce", *params.XSrnNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-nonce", headerParam1)
		}

		if params.XSrnSignature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "x-srn-signature", *params.XSrnSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-signature", headerParam2)
		}

	}

	return req, nil
}

// NewGetV1TmdbSeasonRequest generates requests for GetV1TmdbSeason
func NewGetV1TmdbSeasonRequest(server string, params *GetV1TmdbSeasonParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tmdb/season")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tmdb_id", params.TmdbId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "season", params.Season, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XSrnPubkey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-srn-pubkey", *params.XSrnPubkey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-pubkey", headerParam0)
		}

		if params.XSrnNonce != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-srn-nonce", *params.XSrnNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-nonce", headerParam1)
		}

		if params.XSrnSignature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "x-srn-signature", *params.XSrnSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-srn-signature", headerParam2)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1ChallengeWithResponse request
	GetV1ChallengeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ChallengeResponse, error)

	// GetV1EventsWithResponse request
	GetV1EventsWithResponse(ctx context.Context, params *GetV1EventsParams, reqEditors ...RequestEditorFn) (*GetV1EventsResponse, error)

	// PostV1EventsWithBodyWithResponse request with any body
	PostV1EventsWithBodyWithResponse(ctx context.Context, params *PostV1EventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1EventsResponse, error)

	// GetV1EventsIdContentWithResponse request
	GetV1EventsIdContentWithResponse(ctx context.Context, id string, params *GetV1EventsIdContentParams, reqEditors ...RequestEditorFn) (*GetV1EventsIdContentResponse, error)

	// GetV1RelayWithResponse request
	GetV1RelayWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1RelayResponse, error)

	// GetV1TmdbSearchWithResponse request
	GetV1TmdbSearchWithResponse(ctx context.Context, params *GetV1TmdbSearchParams, reqEditors ...RequestEditorFn) (*GetV1TmdbSearchResponse, error)

	// GetV1TmdbSeasonWithResponse request
	GetV1TmdbSeasonWithResponse(ctx context.Context, params *GetV1TmdbSeasonParams, reqEditors ...RequestEditorFn) (*GetV1TmdbSeasonResponse, error)
}

type GetV1ChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChallengeResponse
}

// Status returns HTTPResponse.Status
func (r GetV1ChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1EventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Events []SRNEvent `json:"events"`
	}
	JSON401 *ErrorResponse
	JSON403 *ErrorResponse
	JSON429 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1EventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1EventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1EventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Deduplicated True when an identical event already exists; id refers to the existing event
		Deduplicated *bool  `json:"deduplicated,omitempty"`
		Id           string `json:"id"`
		Success      bool   `json:"success"`
	}
	JSON400 *ErrorResponse
	JSON401 *ErrorResponse
	JSON403 *ErrorResponse
	JSON413 *ErrorResponse
	JSON429 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostV1EventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1EventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1EventsIdContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON429      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1EventsIdContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1EventsIdContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1RelayResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Name        GetV1Relay200Name   `json:"name"`
		Status      GetV1Relay200Status `json:"status"`
		TotalEvents int                 `json:"totalEvents"`
		Version     string              `json:"version"`
	}
}
type GetV1Relay200Name string
type GetV1Relay200Status string

// Status returns HTTPResponse.Status
func (r GetV1RelayResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1RelayResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1TmdbSearchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Results []TMDBResult `json:"results"`
	}
	JSON401 *ErrorResponse
	JSON403 *ErrorResponse
	JSON429 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1TmdbSearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1TmdbSearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1TmdbSeasonResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		EpisodeCount int `json:"episode_count"`
	}
	JSON401 *ErrorResponse
	JSON403 *ErrorResponse
	JSON429 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1TmdbSeasonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1TmdbSeasonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1ChallengeWithResponse request returning *GetV1ChallengeResponse
func (c *ClientWithResponses) GetV1ChallengeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ChallengeResponse, error) {
	rsp, err := c.GetV1Challenge(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ChallengeResponse(rsp)
}

// GetV1EventsWithResponse request returning *GetV1EventsResponse
func (c *ClientWithResponses) GetV1EventsWithResponse(ctx context.Context, params *GetV1EventsParams, reqEditors ...RequestEditorFn) (*GetV1EventsResponse, error) {
	rsp, err := c.GetV1Events(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1EventsResponse(rsp)
}

// PostV1EventsWithBodyWithResponse request with arbitrary body returning *PostV1EventsResponse
func (c *ClientWithResponses) PostV1EventsWithBodyWithResponse(ctx context.Context, params *PostV1EventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1EventsResponse, error) {
	rsp, err := c.PostV1EventsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1EventsResponse(rsp)
}

// GetV1EventsIdContentWithResponse request returning *GetV1EventsIdContentResponse
func (c *ClientWithResponses) GetV1EventsIdContentWithResponse(ctx context.Context, id string, params *GetV1EventsIdContentParams, reqEditors ...RequestEditorFn) (*GetV1EventsIdContentResponse, error) {
	rsp, err := c.GetV1EventsIdContent(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1EventsIdContentResponse(rsp)
}

// GetV1RelayWithResponse request returning *GetV1RelayResponse
func (c *ClientWithResponses) GetV1RelayWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1RelayResponse, error) {
	rsp, err := c.GetV1Relay(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1RelayResponse(rsp)
}

// GetV1TmdbSearchWithResponse request returning *GetV1TmdbSearchResponse
func (c *ClientWithResponses) GetV1TmdbSearchWithResponse(ctx context.Context, params *GetV1TmdbSearchParams, reqEditors ...RequestEditorFn) (*GetV1TmdbSearchResponse, error) {
	rsp, err := c.GetV1TmdbSearch(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1TmdbSearchResponse(rsp)
}

// GetV1TmdbSeasonWithResponse request returning *GetV1TmdbSeasonResponse
func (c *ClientWithResponses) GetV1TmdbSeasonWithResponse(ctx context.Context, params *GetV1TmdbSeasonParams, reqEditors ...RequestEditorFn) (*GetV1TmdbSeasonResponse, error) {
	rsp, err := c.GetV1TmdbSeason(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1TmdbSeasonResponse(rsp)
}

// ParseGetV1ChallengeResponse parses an HTTP response from a GetV1ChallengeWithResponse call
func ParseGetV1ChallengeResponse(rsp *http.Response) (*GetV1ChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChallengeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV1EventsResponse parses an HTTP response from a GetV1EventsWithResponse call
func ParseGetV1EventsResponse(rsp *http.Response) (*GetV1EventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1EventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Events []SRNEvent `json:"events"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParsePostV1EventsResponse parses an HTTP response from a PostV1EventsWithResponse call
func ParsePostV1EventsResponse(rsp *http.Response) (*PostV1EventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1EventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Deduplicated True when an identical event already exists; id refers to the existing event
			Deduplicated *bool  `json:"deduplicated,omitempty"`
			Id           string `json:"id"`
			Success      bool   `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseGetV1EventsIdContentResponse parses an HTTP response from a GetV1EventsIdContentWithResponse call
func ParseGetV1EventsIdContentResponse(rsp *http.Response) (*GetV1EventsIdContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1EventsIdContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseGetV1RelayResponse parses an HTTP response from a GetV1RelayWithResponse call
func ParseGetV1RelayResponse(rsp *http.Response) (*GetV1RelayResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1RelayResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Name        GetV1Relay200Name   `json:"name"`
			Status      GetV1Relay200Status `json:"status"`
			TotalEvents int                 `json:"totalEvents"`
			Version     string              `json:"version"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV1TmdbSearchResponse parses an HTTP response from a GetV1TmdbSearchWithResponse call
func ParseGetV1TmdbSearchResponse(rsp *http.Response) (*GetV1TmdbSearchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1TmdbSearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Results []TMDBResult `json:"results"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseGetV1TmdbSeasonResponse parses an HTTP response from a GetV1TmdbSeasonWithResponse call
func ParseGetV1TmdbSeasonResponse(rsp *http.Response) (*GetV1TmdbSeasonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1TmdbSeasonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			EpisodeCount int `json:"episode_count"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}
